# 데이터베이스 연결 MongoDB
spring.application.name=ai-code-gem
spring.data.mongodb.uri=mongodb://218.155.183.116:27017/aicodegem
server.port=8080
spring.profiles.active=default
spring.devtools.livereload.enabled=false

# 데이터베이스 연결 MySQL
# spring.datasource.url=jdbc:mysql://218.155.183.116:3306/aicodegem?useUnicode=true&characterEncoding=utf8
# spring.datasource.username=aiuser
# spring.datasource.password=aiCodeGem2014__
spring.datasource.url=jdbc:mysql://localhost:3306/db?useUnicode=true&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=0129
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Spring Boot 애플리케이션의 기본 문자 인코딩 설정
spring.http.encoding.enabled=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true

#jwt 토큰 키 
# application.properties
jwt.secret=W4a1Yl1Kp5+zF1PnYmD3l+kYGl7a2jH8wKsYb3t6lF0=
